### ISSUE TITLE
communication not happening in Production mode 

### ISSUE THREAD

**Issue by kirantpatil** [telegram-bot-rb/telegram_bot_app#7]
I tried in development mode and it is working fine but in production mode communication is not happening.

Please help me to resolve this issue.

My configuration details.

```
development: &dev
  secret_key_base: 3b7f55dd41146764804e122fc94b1e9b9fd86718659a219e8f0828135156dd0245165b215e29d740da4
  telegram:
    bot:
      token: 404717147:xxxxxyyyyzz-GETlwnnetV9olinux3xbrIvuuQjxtvSoz4
      username: kirantest_bot
      async: true
      # botan:
      #   token: botan_token
      #   # async: true
```

telegram_bot_app »  Rails.application.routes.url_helpers.telegram_webhook_url
=> "https://172.104.41.236/telegram/404717147:xxxxxyyyyzz-GETlwnnetV9olinux3xbrIvuuQjxtvSoz4"

### $  bin/rake telegram:bot:set_webhook RAILS_ENV=production
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
Running via Spring preloader in process 3455
Setting webhook for default...

### fueb@localhost:~/telegram_bot_app$ puma -b 'ssl://172.104.41.236?key=webhook_pkey.pem&cert=webhook_cert.pem'
Puma starting in single mode...
* Version 3.6.2 (ruby 2.4.1-p111), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: production
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
* Listening on ssl://172.104.41.236?key=webhook_pkey.pem&cert=webhook_cert.pem
Use Ctrl-C to stop

Thanks.
